# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 23:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_auto_20170718_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 120)),
        ),
        migrations.AddField(
            model_name='user',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 1200)),
        ),
    ]
